# Generated by Django 2.1.2 on 2018-10-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id_captura', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Rostro',
            fields=[
                ('id_rostro', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('intensidad_pix', models.IntegerField()),
                ('cantidad_pix', models.IntegerField()),
                ('estado', models.CharField(max_length=35)),
                ('id_captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Captura')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rostro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Usuario'),
        ),
        migrations.AddField(
            model_name='captura',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Usuario'),
        ),
    ]
