# Generated by Django 2.1.2 on 2018-10-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
