# Generated by Django 2.0.9 on 2018-10-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=1231, max_length=90),
            preserve_default=False,
        ),
    ]
