# Generated by Django 2.1.2 on 2018-10-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capturas',
            fields=[
                ('id_captura', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Rostros',
            fields=[
                ('id_rostro', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('intensidad_pix', models.IntegerField(max_length=150)),
                ('cantidad_pix', models.IntegerField(max_length=150)),
                ('estado', models.CharField(max_length=35)),
                ('id_captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Capturas')),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AddField(
            model_name='rostros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Usuarios'),
        ),
        migrations.AddField(
            model_name='capturas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Usuarios'),
        ),
    ]
