# Generated by Django 2.0.9 on 2018-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_usuario_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rostro',
            old_name='cantidad_pix',
            new_name='cantidad_rostros',
        ),
        migrations.RemoveField(
            model_name='rostro',
            name='intensidad_pix',
        ),
        migrations.AddField(
            model_name='captura',
            name='cantidad_pix',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='captura',
            name='intensidad_pix',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
