# Generated by Django 2.1.2 on 2018-10-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20181023_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capturas',
            new_name='Captura',
        ),
        migrations.RenameModel(
            old_name='Rostros',
            new_name='Rostro',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
